name: CI

on:
  push:
    branches: [master]
    paths:
      - 'src/**/*.purs'
      - 'src/**/*.js'
      - 'test/**/*.purs'
      - 'test/**/*.js'
      - '*.dhall'
      - '*.json'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**/*.purs'
      - 'src/**/*.js'
      - 'test/**/*.purs'
      - 'test/**/*.js'
      - '*.dhall'
      - '*.json'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          purs-tidy: "latest"

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - run: spago install

      - run: spago build --no-install --purs-args '--censor-lib --strict'

      - run: spago -x test.dhall test

      - run: purs-tidy check src test

      - name: Verify Bower & Pulp
        run: |
          npm install bower pulp@16.0.0-0
          npx bower install
          npx pulp build # -- --censor-lib --strict
          npx pulp test